In [2]:
import numpy as np

## 1-D array

In [3]:
# 1-D array indexing

In [9]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [10]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
type(a)

numpy.ndarray

In [12]:
a.dtype

dtype('int32')

In [14]:
np.ndim(a)

1

In [22]:
# indexing

In [19]:
a[1]

1

In [21]:
# slicing

In [23]:
a[0:4]  # start from 0 and end n-1

array([0, 1, 2, 3])

In [43]:
# Reverse 1 - D array
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [32]:
# get last element
a[-1:]

array([9])

In [33]:
a[-1::]

array([9])

In [48]:
a[::2] # get even index ## skip n-1 values

array([0, 2, 4, 6, 8])

In [47]:
a[::3] ## skip n-1 values

array([0, 3, 6, 9])

In [41]:
a[1::2] # get odd index

array([1, 3, 5, 7, 9])

In [44]:
a[-1]

9

In [49]:
##########################################

## 2-D Array

In [50]:
# 2-D Array

In [51]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [52]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
# indexing in 2-D Array

In [54]:
a2[1] ## fetch row wise data

array([4, 5, 6])

In [60]:
a2[1,2]

6

In [62]:
a2[0,2]

3

In [63]:
a2[2,1]

8

In [64]:
## Slicing

In [66]:
a2[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
a2[1:] ## fetch row1 and row 2

array([[4, 5, 6],
       [7, 8, 9]])

In [73]:
a2[1:,2] ## 

array([6, 9])

In [75]:
a2[1:,1:2] ## fetch row1, row2 and col1

array([[5],
       [8]])

In [76]:
a2[:,2] ## fetch column wise data

array([3, 6, 9])

In [77]:
a2[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [78]:
#############################

## 3-d Array

In [78]:
#############################

In [79]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

In [80]:
a3

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

In [81]:
i = np.array([[10,11,12],[13,14,15],[16,17,18]])
i   ### similar to a3[0]  #### i == a3[0]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [92]:
a3[0]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [82]:
j = np.array([[20,21,22],[23,24,25],[26,27,28]])
j    ### similar to a3[1]  #### j == a3[1]

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [93]:
k = np.array([[30,31,32],[33,34,35],[36,37,38]])
k   ### similar to a3[1]  #### k == a3[2]

array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38]])

In [87]:
# indexing a3[i,j,k]   ###[select matrix, select rows, select columns]

In [88]:
;a3[0,2,2]

18

In [89]:
a3[1,2]

array([26, 27, 28])

In [91]:
a3[1]

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [94]:
## slicing

In [95]:
a3[::]  ## same as  a3[0:,0:,0:] 

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

In [102]:
a3[0:,1:,1:]

array([[[14, 15],
        [17, 18]],

       [[24, 25],
        [27, 28]],

       [[34, 35],
        [37, 38]]])

In [106]:
a3[0:,1:,:1]

array([[[13],
        [16]],

       [[23],
        [26]],

       [[33],
        [36]]])

In [109]:
a3[0:,0:,2]

array([[12, 15, 18],
       [22, 25, 28],
       [32, 35, 38]])