In [1]:
import numpy as np

In [2]:
num = [1,2,3]

In [3]:
num

[1, 2, 3]

In [4]:
num = np.array(num)

In [5]:
num

array([1, 2, 3])

In [6]:
num2 = [[1,2,3],[4,5,6]]

In [7]:
num2 = np.array(num2)

In [8]:
num2


array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
num2 = np.ndim(num2)

In [10]:
num2

2

In [11]:
num.shape

(3,)

In [12]:
num.dtype

dtype('int32')

In [13]:
#<h6> #Functions </h6>

In [14]:
#zeros , #ones , #eye, #diag , #radint, #rand, #randn 

In [15]:
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [16]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
arr = np.eye(3)
arr


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
arr = np.diag([1,2,3])
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [20]:
randarry = np.random.randint(1,10,4) 
randarry

array([6, 1, 5, 8])

In [21]:
np.diag(randarry)

array([[6, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 8]])

In [22]:
np.random.rand(2)

array([0.78563654, 0.77670403])

In [23]:
np.random.rand(2,4)

array([[0.1435067 , 0.19376312, 0.02584974, 0.57542174],
       [0.77939894, 0.5002952 , 0.86852298, 0.2926096 ]])

In [24]:
np.random.rand(2,3)

array([[0.92706524, 0.71943665, 0.90740397],
       [0.55503523, 0.03405278, 0.22660505]])

In [25]:
randarry = np.random.rand(4) 
randarry

array([0.4965016 , 0.85369035, 0.48103158, 0.2532038 ])

In [26]:
randarry = np.random.rand(2,3) 
randarry

array([[0.66070634, 0.3652179 , 0.64083326],
       [0.62998779, 0.67613012, 0.41156412]])

In [27]:
randarry = np.random.randn(4) 
randarry

array([-0.31496087, -0.32295054, -0.12728359, -0.6532628 ])

In [28]:
#reshape Data

In [29]:
arr = np.random.randint(1,100,20)
arr

array([39, 37, 37, 67, 33, 28, 73, 46, 79,  4, 88, 58, 36, 82, 87, 91, 88,
       27, 86, 90])

In [30]:
arr.shape

(20,)

In [31]:
arrReshape = arr.reshape(2,10)
arrReshape

array([[39, 37, 37, 67, 33, 28, 73, 46, 79,  4],
       [88, 58, 36, 82, 87, 91, 88, 27, 86, 90]])

In [32]:
arrReshape = arr.reshape(2,10)
arrReshape.shape

(2, 10)

In [33]:
#same random regenerate 

In [34]:
np.random.seed(10)
arr = np.random.randint(1,10,20)

arr

array([5, 1, 2, 1, 2, 9, 1, 9, 7, 5, 4, 1, 5, 7, 9, 2, 9, 5, 2, 4])

In [35]:
arr.size

20

In [36]:
#Array Indexing & Slicing
arr = [0,1,2,3,4,5,6,7,8,9]
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
arr[3]

3

In [38]:
arr[1:5]

[1, 2, 3, 4]

In [39]:
arr[1:8:2]

[1, 3, 5, 7]

In [40]:
# create 2-D Array

In [41]:
import numpy as np

In [42]:
matrix = np.array([[2,4,5],[6,7,8],[3,6,8]])
matrix

array([[2, 4, 5],
       [6, 7, 8],
       [3, 6, 8]])

In [43]:
matrix[0],[2]

(array([2, 4, 5]), [2])

In [44]:
matrix[0][2]

5

In [45]:
matrix[0,2]

5

In [46]:
matrix[0]

array([2, 4, 5])

In [47]:
matrix[0,2]

5

In [48]:
matrix

array([[2, 4, 5],
       [6, 7, 8],
       [3, 6, 8]])

In [49]:
matrix[1:,:2]

array([[6, 7],
       [3, 6]])

In [50]:
##Sliced Copy
arr = np.array([1,3,4,5,6,7,8,9])
arr

array([1, 3, 4, 5, 6, 7, 8, 9])

In [51]:
sliced = arr[0:7:2].copy()
sliced

array([1, 4, 6, 8])

In [52]:
sliced[:] = 0
sliced

array([0, 0, 0, 0])

In [53]:
arr

array([1, 3, 4, 5, 6, 7, 8, 9])

In [54]:
##Conditional Statement

In [55]:
import numpy as np


In [56]:
a  =np.arange(1,11)

In [57]:
#conditional 

a = np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [58]:
a>3

array([False, False, False,  True,  True,  True])

In [59]:
value = a>3
a[value]

array([4, 5, 6])

In [108]:
a[a > 3] = True

In [109]:
a

array([1, 2, 3])

In [60]:
a[a==3]

array([3])

In [61]:
# Operation in Array
a2 = np.arange(11)
# Multiplication
a2 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [62]:
#Square Root **
a2 ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [63]:
#Operation on 2 or more Array
Arr1 = np.array([1,3,4,6,7])
Arr2 = np.array([3,5,6,7,8])


In [64]:
Arr1+Arr2

array([ 4,  8, 10, 13, 15])

In [65]:
np.random.seed(123)
matrix1 = np.random.randint(1,12,9).reshape(3,3)
matrix2 = np.random.randint(5,15,9).reshape(3,3)



In [66]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [67]:
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [68]:
matrix1*matrix2

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [69]:
##Function

In [70]:
np.random.seed(123)
number = np.random.randint(1,10,20)
number

array([3, 3, 7, 2, 4, 7, 2, 1, 2, 1, 1, 4, 5, 1, 1, 5, 2, 8, 4, 3])

In [71]:
np.min(number)

1

In [72]:
np.max(number)

8

In [73]:
## position of minimum number
np.argmin(number)


7

In [74]:
## position of maximum number
np.argmax(number)


17

In [75]:
np.sqrt(number)

array([1.73205081, 1.73205081, 2.64575131, 1.41421356, 2.        ,
       2.64575131, 1.41421356, 1.        , 1.41421356, 1.        ,
       1.        , 2.        , 2.23606798, 1.        , 1.        ,
       2.23606798, 1.41421356, 2.82842712, 2.        , 1.73205081])

In [76]:
boolean = np.array([1,2,3,0,1,0,0,3], dtype = 'bool')
boolean

array([ True,  True,  True, False,  True, False, False,  True])

In [112]:
np.random.seed(123)
matrix = np.random.randint(1,10,9).reshape(3,3)
matrix

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [113]:
np.min(matrix)

1

In [79]:
## row = 1 , column = 0 >> Find minimum row wise
np.min(matrix, axis = 1)

array([3, 2, 1])

In [80]:
np.max(matrix, axis = 0)

array([3, 4, 7])

In [81]:
np.sum(matrix, axis = 1)

array([13, 13,  5])

In [82]:
np.cumsum(matrix)

array([ 3,  6, 13, 15, 19, 26, 28, 29, 31], dtype=int32)

In [83]:
np.cumsum(matrix, axis = 1)

array([[ 3,  6, 13],
       [ 2,  6, 13],
       [ 2,  3,  5]], dtype=int32)

In [84]:
np.prod(matrix, axis = 1)

array([63, 56,  4])

In [85]:
np.prod(matrix, axis = 0)

array([12, 12, 98])

In [86]:
np.random.seed(123)
shuffle_array = np.random.randint(1,15,20)
shuffle_array

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10,  1,  1,
       10,  4, 14])

In [114]:
a = np.random.shuffle(matrix)

In [115]:
a

In [89]:
np.unique(shuffle_array)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [90]:
np.unique(shuffle_array).size

10

In [91]:
## shuffle_array >> return array , return_index >> return position ,return_counts >> return number of occurance
np.unique(shuffle_array , return_index = True, return_counts = True)

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([12,  5,  1,  6,  4,  9,  7,  8,  2,  0], dtype=int64),
 array([3, 3, 2, 2, 2, 3, 1, 1, 1, 2], dtype=int64))

In [92]:
import numpy as np



In [93]:
matrix1 = np.random.randint(0,8,9).reshape(3,3)
matrix2 = np.random.randint(10,18,9).reshape(3,3)


In [94]:
matrix1

array([[0, 4, 1],
       [7, 3, 2],
       [4, 7, 2]])

In [95]:
matrix2

array([[14, 17, 10],
       [15, 10, 17],
       [11, 13, 14]])

In [96]:
np.hstack((matrix1, matrix2))

array([[ 0,  4,  1, 14, 17, 10],
       [ 7,  3,  2, 15, 10, 17],
       [ 4,  7,  2, 11, 13, 14]])

In [97]:
np.vstack((matrix1, matrix2))

array([[ 0,  4,  1],
       [ 7,  3,  2],
       [ 4,  7,  2],
       [14, 17, 10],
       [15, 10, 17],
       [11, 13, 14]])

In [98]:
a = np.random.randint(1,4,3).reshape(1,3)
a

array([[1, 1, 3]])

In [99]:
import numpy as np

In [116]:
a = np.arange(1,4)

In [117]:
a

array([1, 2, 3])