In [2]:
import numpy as np

In [2]:
print(np.__version__)

1.19.2


In [3]:
mat1 = np.arange(1,10)

In [5]:
mat1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
mat2= np.arange(1,10).reshape(3,-1)
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# Alternatative hstack and vstack is np.concatenate([a, b], axis=0/1)

In [12]:
np.concatenate([mat1, mat2],axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.concatenate([mat1, mat2],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [14]:
a = np.array([1,2,3])

In [15]:
a

array([1, 2, 3])

In [17]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [18]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [20]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [21]:
#find comman items from array

In [22]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [23]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [24]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [25]:
np.intersect1d(a,b)

array([2, 4])

In [28]:
## How to remove from one array those items that exist in a

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)
#> array([1, 2, 3, 4])


array([1, 2, 3, 4])

In [30]:
## How to get the positions where elements of two arrays match

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)
#> (array([1, 3, 5, 7]),)

(array([1, 3, 5, 7], dtype=int64),)

In [31]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [32]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [4]:
num = np.arange(0,101,2)
num

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [5]:
## Multiplication of 2 matrix
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])
print(a*b)

[[ 2  6 12]
 [20 30 42]
 [56 72 90]]


In [6]:
print(a@b)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [7]:
 np.matmul(a, b)


array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [14]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b

c

array([1, 5, 7, 7, 9])

In [15]:
c= c*a
c

array([ 1, 10, 21, 35, 72])